### ISSUE TITLE
Hook arguments and return values are not composable

### ISSUE THREAD

**Issue by Pet3ris** [apibara/starknet-react#103]
I'm running into situations where an output of one call needs to be composed as the input to another contract call. Unfortunately, it seems that current argument types are based on arrays of strings and current output types have more type information (for example returning `BN.js` types).

I wonder if it would make sense to decide on a default in-js representation for felts and other types and using it consistently?

Perhaps related to this: https://github.com/apibara/starknet-react/issues/98.

**Comment by fracek** [comment]
I agree with that, need to send a PR to starknet.js to have more consistent types for calls inputs and outputs.

**Comment by Pet3ris** [comment]
Thanks @fracek for the triage. I'll update my mental model of this library as a lightweight wrapper :)!

**Comment by Pet3ris** [comment]
@fracek - curious, did they fix it?

**Comment by fracek** [comment]
My understanding is that [this commit from february](https://github.com/0xs34n/starknet.js/commit/3f7425ff0ac29dda2a7c9373856a4aa20002af9b) fixed it.
