### ISSUE TITLE
Introduce hooks for low-level contract calls and invocations

### ISSUE THREAD

**Issue by Pet3ris** [apibara/starknet-react#104]
There are some use cases which may mandate using the low-level `starknet.js` operations `callContract` and `invokeFunction`. However, today, no hook api exists for them. This is particularly useful in StarkNet where we don't need the full contract signature to call a function.

Examples:

- Rapid prototyping (e.g., only need to call 1 function without providing abi)
- Low-level interactions (e.g., trading/MEV contracts in ethereum mainnet)
- Security testing of contracts

**Comment by fracek** [comment]
Agree with this. We should add the following hooks:

 * `useProviderCall` that has the same behaviour as the current call hook, but calls `provider.callContract`
 * `useProviderInvoke` that uses `provider.invokeFunction`

**Comment by fracek** [comment]
Another way to do this, change `useStarknetCall` to:

```ts
function useStarknetCall({ contractOrAddress }: { contractOrAddress?: string | Contract })
```

If it's a `Contract`, then the behaviour is the same as today. If it's a string, then it uses `callContract`. 

For invoke, I think using `useStarknetExecute` is enough?

**Comment by J4ckyLIM** [comment]
Is it still open ? I would like to work on this one if possible

**Comment by fracek** [comment]
Someone else is working on this as part of moving everything to a wagmi-like API.

**Comment by fracek** [comment]
This is now the default behaviour thanks to starknet.js `populateTransaction`.
