### ISSUE TITLE
Allow to disable autorefresh when using `useStarknetCall`

### ISSUE THREAD

**Issue by ltoussaint** [apibara/starknet-react#106]
I have a use case where the data of a contract will never change.
For this reason I want to prevent my app to refresh those data and I can only do it using `starknet.js`

As auto-refresh is a great feature, we should give the possibility to disabled this auto refresh.
Maybe
- with an option to the `useStarknetCall` hook
-  by creating a specific hook
- or maybe by leveraging on the new hook from this issue #104?

**Comment by Pet3ris** [comment]
+1, this would be useful. It also comes as part of the wagmi api: https://wagmi.sh/docs/hooks/useContractRead#watch-optional.

Related: https://github.com/apibara/starknet-react/issues/105

**Comment by fracek** [comment]
Agree.

**Comment by fracek** [comment]
Included in #120
