### ISSUE TITLE
Replace combination of `useEffect` + `setState` by `useMemo`

### ISSUE THREAD

**Issue by ltoussaint** [apibara/starknet-react#107]
I take the example of `useContract` which use this combination.

It would give better performance and more readability to use `useMemo` instead.

Plus, we will not have to wait for `setState` to be called to be able to use the contract.
When using `useContract`, we have to deal with the possibility that the contract is undefined, which will not be the case when using `useMemo`.

Here is a little post which explain this : https://stackoverflow.com/a/56029184

**Comment by fracek** [comment]
Good catch, I will update it.

**Comment by fracek** [comment]
Done in #120
