### ISSUE TITLE
Eth contract: bug with hooks, but not with the other syntax (ethContract.approve(...) for example)

### ISSUE THREAD

**Issue by Marchand-Nicolas** [apibara/starknet-react#134]
```js

  const { data:approveData, approveLoading, error:approveError, reset:approveReset, invoke:approve } = useStarknetInvoke({ ethContract, method: 'approve'})

  // It doesn't work
  useEffect(() => {
    ethContract && approve({ args: ['0x6806c42960e739918af543b733e76eb4f52a99402ec00e57794cb26cb3a6723', [100000000, 0]] })
  }, [ethContract, approve])
  // It doesn't work
  ethContract && approve({ args: ['0x6806c42960e739918af543b733e76eb4f52a99402ec00e57794cb26cb3a6723', [100000000, 0]] })
  
  // It works
  ethContract && ethContract.approve('0x6806c42960e739918af543b733e76eb4f52a99402ec00e57794cb26cb3a6723', [100000000, 0])

```

(when it doesn't work, absolutely nothing happens, no error)

Here is the eth contract : https://goerli.voyager.online/contract/0x4bb0f7af15a5469be4a571c8660d9aaf39e7e67f27f774702d75e77141ef90#writeContract

![image](https://user-images.githubusercontent.com/60229704/175068736-b65df92a-6082-4ccb-8dc3-ad5bef664293.png)

Here is the eth contract ABI : 
https://pastebin.com/YxyfivFr

I also tried : 
![image](https://user-images.githubusercontent.com/60229704/175069243-b1619c85-d7df-4d69-baca-d4e2774a9d3b.png)

**Comment by fracek** [comment]
This should be fixed in v2. If not, feel free to reopen.
