### ISSUE TITLE
`get-starknet` breaks ArgentX wallet integration

### ISSUE THREAD

**Issue by Pet3ris** [apibara/starknet-react#135]
It seems that the latest version mandates using `get-starknet` as opposed to the connectors approach which was used before. While it's great that users can now choose their preferred wallet, unfortunately, the popup is not showing to some of our users (including myself) on Chrome; even if they have ArgentX installed. It works fine on the Brave browser.

Any idea what could be causing the inconsistency in behavior?

**Comment by fracek** [comment]
I believe this will be fixed by #127. I will try find time today to get it merged.

**Comment by Pet3ris** [comment]
Can confirm that this now works :).
