### ISSUE TITLE
Check user connected network after connecting wallet

### ISSUE THREAD

**Issue by kootsZhin** [apibara/starknet-react#142]
At the moment there seems to be no support in checking which network the user is connected to (e.g. Goeril or mainnet), i.e. the `chainId`.

It would be nice if we could possibly add some new features (e.g. hooks) for checking this - similar to what we have for `chainId` in [wagmi](https://github.com/tmm/wagmi) for EVM chains.

This is crucial because when mainnet launch we would not want the users to sign the message on the wrong network to cause any inconvenience or financial loss.

**Comment by fracek** [comment]
I agree with this. The hook should also listen for network changed events on the wallet to keep the current network updated.

**Comment by onlydust-contributor** [comment]
@clementjuventin is going to work on this contribution

**Comment by J4ckyLIM** [comment]
Is it still open ? If yes can I work on it ?

**Comment by clementjuventin** [comment]
It seams like I did it:

https://github.com/apibara/starknet-react/pull/167

**Comment by fracek** [comment]
Yep, forgot to close this issue when I merged your PR manually.
