### ISSUE TITLE
Bug with multicall: Connector not connected

### ISSUE THREAD

**Issue by Th0rgal** [apibara/starknet-react#156]
Hello,

It seems I have a bug with multicall and hardcoded connectors. I get the error "Connector not connected" when trying to do a multicall even though I am connected through argent-x.

Here is the repo at the right commit to reproduce it:
https://github.com/starknet-id/app.starknet.id/blob/98569303571a40040da1bbbb890a76b48e68ef38/components/domains/register.tsx

**Comment by fracek** [comment]
I was able to send an approve multicall tx to approve the token (see [here](https://goerli.voyager.online/tx/0x6e03b276d00bfceb3504eed73cc4aaeec5b9515462c1967b7510b7cfff5b1f3)), so the issue seems to be related to something else. Will investigate further.

**Comment by Th0rgal** [comment]
After some testings, it appears I only had that issue with argent-x. After installing Braavos it worked ...on Bravos and Argent-x.

**Comment by fracek** [comment]
After more investigation, me and @Th0rgal  found that it seems related to specifying multiple connectors but then the user only has one wallet installed.
