### ISSUE TITLE
getInstalledInjectedConnectors() may be empty on page load but not empty a bit later

### ISSUE THREAD

**Issue by nmalzieu** [apibara/starknet-react#168]
On pxls.wtf we had the following issue: sometimes the users couldn't log because there were no connectors.
I found that it happened when the user was reloading the page (command R on chrome).
At that point, the `getInstalledInjectedConnectors()` that gets called at the very beginning of my Next.js app was empty!

Right now, I fixed it the hacky way:
https://github.com/nmalzieu/pxls-frontend/blob/main/pages/_app.tsx#L111-L129

However, I wonder:
- could we detect that the installed connectors available on the page have changed?
- should we really check this just once, at the very beginning of a Next.js app as done[ in the example](https://github.com/apibara/starknet-react/blob/main/examples/starknet-react-next/pages/_app.tsx#L6) or should we have a way to reload this before trying to connect
- is there a reason why this happened to me only when doing a "reload" of the page and not when I was opening the same page in a new tab?

**Comment by fracek** [comment]
This is a long standing issue and as you say there is no clear way forward. The wallets inject themselves at any point after the page loads and so it's impossible to detect them reliably. My guess is that users that experience issues have many extensions installed or slower computers. In your case, when you reload the page maybe chrome uses the cached version of the application and so the code is executed before the wallets finished injecting themselves.

The solutions are two:

 - manually create a list of supported wallets
 - use a hook similar to yours to refresh the installed wallets periodically

I wish we had a way to listen for changes to the window object to detect the wallets better.

**Comment by nmalzieu** [comment]
Thanks for your quick answer! 
I wonder if we shouldn't see connectors in 2 groups:
- connectors that we manually pass to the provider
- injected installed connectors that we find in the window object

When we use injected connectors, maybe we should just make the `connectors` and `available` properties of `useStarknet` methods that actually refresh them?

Do you know how wagmi handles this on Ethereum? They should have the exact same issue?

**Comment by fracek** [comment]
In wagmi you need to specify the connectors manually so there is no issue. I agree `connectors` and `available` should be functions not values, probably a good idea to do that in the next breaking release.
