### ISSUE TITLE
`autoconnect` reconnects to the wrong wallet after refresh when connecting to multiple wallets

### ISSUE THREAD

**Issue by YohanTz** [apibara/starknet-react#170]
I tried connecting to Argent X, then disconnect from it and then connect to Braavos. After I hit refresh, I was connected to my Argent X wallet, while I was expecting to be connected to my Braavos wallet

**Comment by fracek** [comment]
This is because the library is stateless, so it cannot track the last connected wallet.

We should add an option to use local storage to track of this.

**Comment by YohanTz** [comment]
Ok I see ! I can work on it if needed 👍🏽 You can give me some pointers on how you want it to be implemented if you want 😄

**Comment by fracek** [comment]
Fixed in #186
