### ISSUE TITLE
Create type-safe ABI encoder/decoder

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#178]
We should create a type-safe encoder/decoder (based on #177) that then we can leverage in our hooks. This fixes #98

**Comment by davelange** [comment]
I know this is an old issue, and the best option long term is maybe using [abi-wan](https://github.com/keep-starknet-strange/abi-wan-kanabi), but for now maybe it would be a good idea to tackle a smaller part of this problem?

Right now the return value of `useContractRead` is basically `any[]`, which makes it hard to use. I think I can implement a version where at least it types the `functionName`, and returns
```
{
   returnKey1: unknown
   returnKey2: unknown
}
```
Not a problem if anyone is already on this though.

**Comment by fracek** [comment]
I think the goal is to replace it with `abi-wan`. Maybe we can find a way to integrate the library in the `useContractRead` hook?

**Comment by davelange** [comment]
I agree, Though at the moment I dont think abi-wan it ready for that yet

**Comment by fracek** [comment]
I feel this issue is basically blocked by starknet.js/abi-wan. So nothing much we can do about it :(

**Comment by davelange** [comment]
Yeah, that's a shame :frowning_face: In any case, I have a sort of working version on [this branch](https://github.com/finiam/starknet-react/blob/dl/abi-typing/packages/core/src/hooks/call.ts )

**Comment by fracek** [comment]
ABI wan fixed this.
