### ISSUE TITLE
Update account with the `connector.connect()` method

### ISSUE THREAD

**Issue by JaniAnttonen** [apibara/starknet-react#198]
https://github.com/apibara/starknet-react/blob/32915f13675cf76d9b4a31b0a57f548cd18df468/packages/core/src/connectors/injected.ts#L59

The method on this line does not seem to currently update the account that's given by the `useAccount()` hook. Account updates fine when connecting with the function `connect(connector)`.

This problem was encountered when using these hooks in Nextjs. Let's look at the example in: https://github.com/apibara/starknet-react/blob/32915f13675cf76d9b4a31b0a57f548cd18df468/packages/core/src/hooks/connectors.ts#L32
If you replace the onClick listener to:
```tsx
function Component() {
  const { connect, connectors } = useConnectors()

  return (
    <ul>
      {connectors.map((connector) => (
        <li key={connector.id()}>
          <button onClick={() => connector.connect()}> // instead of connect(connector)
            Connect {connector.id()}
          </button>
        </li>
      ))}
    </ul>
  )
 }
```
, this does not update:
```tsx
const { account } = useAccount()
```

**Comment by fracek** [comment]
It's not 100% clear what you mean. Do you have a way to reproduce this issue?

**Comment by fracek** [comment]
This should be fixed in v2. If not, feel free to reopen.
