### ISSUE TITLE
Create a hook to get starknet id stark domain or address

### ISSUE THREAD

**Issue by fricoben** [apibara/starknet-react#202]
As we discussed we @fracek already, it could be cool to add starknet.id to starknet-react using [this](https://www.starknetjs.com/docs/API/account).

<img width="871" alt="Capture d’écran 2022-12-14 à 18 51 22" src="https://user-images.githubusercontent.com/78437165/207670043-c5db1d5a-e753-4edb-a8a4-f0d00d348827.png">

We can add `useStarkName` and `useAddrFromStarkName`, should be really easy considering the fact that all the complexity is in starknet.js

Thanks !

**Comment by 0xYami** [comment]
Hey guys, can I give a shot to this one?

**Comment by 0xYami** [comment]
If you are okay with that, I just had a quick look and it seems that `getStarkName()` and `getAddressFromStarkName()` are both not correctly exposed. I acknowledge this feature was added on `starknet.js` by this [PR](https://github.com/0xs34n/starknet.js/pull/400) and released in `v4.15.0`.

From the discussions, it seems they have been omitted intentionally from `AccountInterface`.
Would you be okay to extend this interface here or should I open an issue in `starknet.js`?

**Comment by 0xBenaparte** [comment]
I think we need to extend the interface here cause the fact that these functions were not in the Interface was the reason why they let this PR be merged, so no need to create any issue on `starknet.js`. 

I'll let @fracek decide, he is the one in charge here ;).

**Comment by fracek** [comment]
So if i understand correctly, the methods are part of `Account` but not of `AccountInterface`?

**Comment by 0xBenaparte** [comment]
Yes

**Comment by fracek** [comment]
What if we had the two following hooks:

```
const { ... } = useStarkName({ address, contract })
const { ... } = useAddressFromStarkName({ name, contract })
```

(where contract is optional). You can implement them using the helper functions already included in starknet.js, but without the need to patch `AccountInterface`.

**Comment by 0xYami** [comment]
It would not make TypeScript happy since it looks at `AccountInterface` to know which methods are defined, i.e the following would not work

```ts
function useStarkName(props) {
  const { account } = useAccount();
  
  useEffect(() => {
    (async () => {
      // Error: Property 'getStarkName' does not exist on type 'AccountInterface'
      account?.getStarkName()
    })()
  , [account])
}
```

We could fix that by extending`AccountInterface` globally

```ts
// starknet.d.ts
import type { AccountInterface } from 'starknet'

declare module 'starknet' {
  interface AccountInterface extends AccountInterface {
    getStarkName(contractId?: string): Promise<string | Error>
    getAddressFromStarkName(name: string, contractId?: string): Promise<string | Error>
  }
}
```

This way we don't need to update all imports to use our custom `AccountInterface`

**Comment by fracek** [comment]
What if the app needs to lookup the starknet name of a non-connected wallet? Apps like snapshot show the list of delegates with their ens name.

**Comment by 0xYami** [comment]
Good point, maybe using `useStarknet()` then fetching `starkName` with react-query would be better

**Comment by 0xBenaparte** [comment]
`What if the app needs to lookup the starknet name of a non-connected wallet? Apps like snapshot show the list of delegates with their ens name.`

More than that there are block explorers that need to fetch the address of non connected accounts. To me the best way is something like that : 

`const { ... } = useStarkName({ address, contract })
const { ... } = useAddressFromStarkName({ name, contract })`

**Comment by 0xYami** [comment]
I will draft something today, roughly I'm thinking of something like that

```ts
function useStarkName({ address, contract }) {
  const { library } = useStarknet()

  const { data, isLoading, isSuccess, isError, error } = useQuery({
    queryKey: ['starkName'],
    queryFn: async () => {
      const account = new Account(library, address, null)
      return account.getStarkName(contract)
    },
  })

  return { data, isLoading, isSuccess, isError, error }
}
```

Something similar for `useAddressFromStarkName({ starkName, contract })` except that here `contract` would be required or fallback to an address like `starknetId` contract address

**Comment by fracek** [comment]
I like this implementation! Contract should be nullable so it defaults to the default one.

**Comment by 0xBenaparte** [comment]
Like it too ! In fact I created the argument `contract` mainly for testing purposes on local environnements. (`starknet-dev`...)
