### ISSUE TITLE
:bug: ensureWallet is now async but InjectedConnector don't use await 

### ISSUE THREAD

**Issue by florian-bellotti** [apibara/starknet-react#227]
Because InjectedConnector is now using get-starknet, the ensureWallet function is now asynchronous. You can see this in this commit: https://github.com/apibara/starknet-react/commit/7a28a8107bc16ecf9e1a11a14837cbb5f0668996. 

However, no function awaits the result of `this.ensureWallet()`.

This bug is easy to solve for all ensureWallet usages except for the `available`,`id`, and `name` functions, which are not asynchronous.

What should we do? Should we make those functions async, or should we call this.ensureWallet() elsewhere?

**Comment by fracek** [comment]
the solution in the PR looks good.
