### ISSUE TITLE
Add useBalance hook

### ISSUE THREAD

**Issue by davelange** [apibara/starknet-react#236]
wagmi has a `useBalance` hook, specifically for fetching balance of Ethereum/ERC-20 tokens, with the benefit that it auto formats the return value based on the decimals you specify.

I think this would be nice to have available in this lib. Does this make sense? I could stark work on this.

Thanks!

**Comment by fracek** [comment]
Yep, this is a good idea! I think someone already contacted me about this before, was it you? Anyway, feel free to open a PR for this and I'll review it
