### ISSUE TITLE
Update website to Next.js 13 `app/` directory

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#238]
We should take advantage of all the new features in next.js 13, like React Server Components.

At the moment, the website uses chakra ui which is not compatible with RSC.

  * Switch to [shadcn ui](https://ui.shadcn.com/) while keeping the current color scheme.
  * Use RSC for the layout, and client components for navigation and code samples.
  * We should investigate using [rehype pretty code](https://rehype-pretty-code.netlify.app/) for code blocks.

**Comment by fracek** [comment]
This [demo from vercel](https://app-dir.vercel.app/context) is useful to understand what's new in next 13.

**Comment by Laki997** [comment]
I will be on it.

**Comment by fracek** [comment]
This is now done.
