### ISSUE TITLE
Add `use client` to `StarknetConfig`

### ISSUE THREAD

**Issue by Pet3ris** [apibara/starknet-react#239]
Right now `StarknetConfig` cannot be used directly in Vercel app router without creating a wrapper component with `use client`.

See this discussion by Vercel:

https://nextjs.org/docs/getting-started/react-essentials#context

Here is their recommendation for library maintainers and a temporary fix:

![image](https://github.com/apibara/starknet-react/assets/224585/d126453c-feb1-4615-9b88-3a305acf9a2a)

**Comment by fracek** [comment]
Starknet React now works with Next.js 14.
