### ISSUE TITLE
error in `InjectedConnector.ensureWallet()` after upgrading to `0.17.1`

### ISSUE THREAD

**Issue by iddriss** [apibara/starknet-react#245]
While using the `useConnectors()` hook, the following error occurred when accessing `connector` methods after upgrading to version [v0.17.1](https://github.com/apibara/starknet-react/releases/tag/%40starknet-react%2Fcore%400.17.1) from [v0.14.6](https://github.com/apibara/starknet-react/releases/tag/%40starknet-react%2Fcore%400.14.6)

<img width="708" alt="Screenshot 2023-05-25 at 11 51 37 AM" src="https://github.com/apibara/starknet-react/assets/25664628/39f3ae3d-af86-45b4-95f2-1d057b4f7854">

It appears the error only occurs for methods that use `ensureWallet()`. The error indicates that `.getStarknet` is not a function, however tracing back to the line show `.getStarknet` is in fact a function. 

<img width="708" alt="Screenshot 2023-05-25 at 11 57 08 AM" src="https://github.com/apibara/starknet-react/assets/25664628/8a208830-2642-423c-b4a0-e7994fbb37e9">

**Comment by fracek** [comment]
It looks like something strange with `get-starknet` or `get-starknet-core`. Requires further investigation.

**Comment by fracek** [comment]
I tried to reproduce the issue with the following steps:

 * create a new project with `npx create-starknet`, selecting the next.js template
 * update the `@starknet-react/core` version to '^0.17.2'
 * run `npm update`
 * check that the lock file contains the updated version of starknet react
 * load the main page `npm run dev` and connect the wallet. The `WalletBar` component uses `useConnectors` so it should trigger this issue.

Unfortunately I did not get any error. Can you try to run the same steps as me and see if there is any issue?

**Comment by iddriss** [comment]
Alright, I'll try that

**Comment by fracek** [comment]
Are you using `create-react-app` by any chance? In that case, it could be this issue https://github.com/facebook/create-react-app/pull/12021

If you attach a debugger in the browser, you should see something like this (notice the .cjs extension)
![2023-05-27-113234_649x347_scrot](https://github.com/apibara/starknet-react/assets/282580/25c19615-8ce3-41d8-a86b-58cf78be974c)

**Comment by fracek** [comment]
I was able to fix the issue my monkey patching the webpack config used by cra. [Here is the commit that shows exactly how to do it](https://github.com/fracek/cra-cjs-fix/commit/d283a64f3fe825ad2f0a1a0945cf0aac67d25e8a)

**Comment by iddriss** [comment]
> I was able to fix the issue my monkey patching the webpack config used by cra. [Here is the commit that shows exactly how to do it](https://github.com/fracek/cra-cjs-fix/commit/d283a64f3fe825ad2f0a1a0945cf0aac67d25e8a)

This fixed my issue. Thanks for helping with the problem.

**Comment by iddriss** [comment]
Ended up using this

https://github.com/facebook/create-react-app/issues/12700#issuecomment-1463040093

somehow the `cjs` file was still processed as a static file after building . Works perfectly on while using running the start script.

> ```ts
> export default {
>   webpack: {
>     configure: config => ({
>       ...config,
>       module: {
>         ...config.module,
>         rules: config.module.rules.map(rule => {
>           if (rule.oneOf instanceof Array) {
>             // eslint-disable-next-line no-param-reassign
>             rule.oneOf[rule.oneOf.length - 1].exclude = [
>               /\.(js|mjs|jsx|cjs|ts|tsx)$/,
>               /\.html$/,
>               /\.json$/,
>             ];
>           }
>           return rule;
>         }),
>       },
>     }),
>   },
> };
> ```
