### ISSUE TITLE
update starknet dependency version to 5.9.1

### ISSUE THREAD

**Issue by rjnrohit** [apibara/starknet-react#253]

**Comment by fracek** [comment]
I agree with this. From our discussion on telegram my understanding is the following:

 * `get-starknet` and wallets return an object that implements the `AccountInterface` v4
 * starknet.js requires now the `AccountInterface` v5

My idea is that for the time being we should wrap the account v4 into a shim that implements the account v5 interface (and throws if the library/dev tries to use a new method).

What do you think?

**Comment by fracek** [comment]
v5 is now supported.
