### ISSUE TITLE
`isConnecting` from `useAccount` is always false

### ISSUE THREAD

**Issue by YohanTz** [apibara/starknet-react#266]

**Comment by fracek** [comment]
Should it be `true` while awaiting for the user to confirm the connection right?

**Comment by YohanTz** [comment]
Exactly 👍🏽  Or when the wallet is auto-connecting on page load

**Comment by YohanTz** [comment]
Working on it

**Comment by fracek** [comment]
This should be fixed in v2. If not, feel free to reopen.
