### ISSUE TITLE
`connectors` getters throw an ESLint error with the V1 release

### ISSUE THREAD

**Issue by YohanTz** [apibara/starknet-react#279]
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/unbound-method.md#examples
<img width="1013" alt="Screenshot 2023-07-04 at 17 50 33" src="https://github.com/apibara/starknet-react/assets/37301269/bef15d38-7063-403e-af51-672189316984">

**Comment by fracek** [comment]
Interesting. I don't understand where the issue comes from, is it `connector.id`?

**Comment by YohanTz** [comment]
> Interesting. I don't understand where the issue comes from, is it `connector.id`?

Yes ! `connector.id` and ˋconnector.name`

**Comment by fracek** [comment]
I will look into this. Seems it doesn't like the new abstract properties (that's the only change since v0).

**Comment by fracek** [comment]
This should be fixed in v2. If not, feel free to reopen.
