### ISSUE TITLE
unpin the starknet version

### ISSUE THREAD

**Issue by moodysalem** [apibara/starknet-react#282]
https://github.com/apibara/starknet-react/blob/a725fa891960f95a0dbf8994a420ff23f2738e34/package.json#L43

this should be ^5.12.0

why is it locked to 5.12? it forces me to have 2 versions of starknet in my app

**Comment by fracek** [comment]
That's true. Let me fix this now.

**Comment by fracek** [comment]
I see it sneaked it somehow. I saw it in peerDependencies and didn't check dependencies. Will fix now.

**Comment by fracek** [comment]
Feel free to reopen if the fix actually didn't fix it 😅
