### ISSUE TITLE
Web: invalid nav links to home

### ISSUE THREAD

**Issue by iddriss** [apibara/starknet-react#287]
on the Starknet React website, navigating to any page and clicking on `Home` or `Starknet React` take you to `https://apibara.github.io/starknet-react.txt` which doesn't exist.

<img width="500" alt="Screenshot 2023-07-10 at 11 44 37 PM" src="https://github.com/apibara/starknet-react/assets/25664628/2dccf1ea-8fb4-4eb1-b895-77830682bcc5">

**Comment by fracek** [comment]
I noticed this bug was introduced after the RSC update. I believe the fix is to change the link to end with `/`.

**Comment by fracek** [comment]
This should be fixed in v2. If not, feel free to reopen.
