### ISSUE TITLE
Upgrade documentation to use typedoc 0.24.8

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#288]
We should update typedoc and use this update as an excuse refactor the documentation page to take full advantage of RSC. When upgrading typedoc the website stops working because it tries to access `fs` from a client component, this is bad but we can use it to guide us through the refactor.

At the moment, because we use too many hooks to compute stuff like remarks, deprecation, etc, the entire page is a client component (green box in the screenshot).

The plan is to refactor aggressively and make only the code blocks and interactive area client components, leaving the rest a RSC (no `use client` directive)(pink boxes in the image).

![2023-07-12-131748_712x817_scrot](https://github.com/apibara/starknet-react/assets/282580/b102027a-5169-4fc3-907c-a2bc43537314)

**Comment by Laki997** [comment]
I will be on it.

**Comment by fracek** [comment]
done in #290
