### ISSUE TITLE
batch calls via multicall

### ISSUE THREAD

**Issue by moodysalem** [apibara/starknet-react#291]
sending 1 rpc per call can lead to getting throttled

instead, batch the calls into a rpc that calls a contract that allows you to call many other contracts and returns all the data in an array of structs

**Comment by fracek** [comment]
Agree. Let's see if we can add it to starknet react or maybe it needs to be part of starknet.js ([like viem](https://viem.sh/docs/clients/transports/http.html#batch-json-rpc)).

**Comment by moodysalem** [comment]
> Agree. Let's see if we can add it to starknet react or maybe it needs to be part of starknet.js ([like viem](https://viem.sh/docs/clients/transports/http.html#batch-json-rpc)).
> 
> Or do you mean to create and deploy a multicall contract and use that to batch calls?

yeah a multicall contract would be good _iff_ there is no way to send a batch json rpc call

the only other reason multicall is useful is because infura counts per request for billing, rather than for complexity of the request, so making one big multicall is cheaper than many smaller calls
