### ISSUE TITLE
Web Wallet connector id

### ISSUE THREAD

**Issue by fricoben** [apibara/starknet-react#292]
For knowing if the web wallet is connected or no in starknet react it’s tricky because we have to use `connector.id()` when it’s `connector.id` for normal wallets.

**Comment by YohanTz** [comment]
I think that he is talking about this package from Argent `@argent/starknet-react-webwallet-connector`

**Comment by fracek** [comment]
It's a bug in that library, they should implement the interface from v1. /cc @dhruvkelawala

**Comment by dhruvkelawala** [comment]
Agree. Thanks for bringing this up

**Comment by dhruvkelawala** [comment]
Confirmed with the team, it's already done and will be in the release today or tomorrow.

**Comment by fracek** [comment]
Thank you for the quick response and fix! Going to close.
