### ISSUE TITLE
throw an error if the called function is not in the abi

### ISSUE THREAD

**Issue by moodysalem** [apibara/starknet-react#293]
ideally it's a compile time error, but at least throw a runtime error. when i updated my abis it was difficult to find all the places that i was calling nonexistent functions

**Comment by fracek** [comment]
It will become a compile time error once starknet.js v6 is released. For now I agree it's a good idea to throw an error.

**Comment by fracek** [comment]
1.0.4 was released with this. If the function is missing in the abi you'll see an error in the console.

Once starknet.js v6 is released we can add compile-time checks.
