### ISSUE TITLE
Multiple wallet popups when wallet is locked

### ISSUE THREAD

**Issue by Sahitya777** [apibara/starknet-react#298]
https://apibara.github.io/starknet-react/hooks/useConnectors
When we use this hook, let's say the user has signed the wallet and connects to the website but when the user locks the wallets or let's say he visits the same website the next day the wallet is locked so what the hook does it automatically calls the wallet popup for signup but there is  a problem that mutiple popups comes up during that process.
![image](https://github.com/apibara/starknet-react/assets/77379621/7beed12b-9df6-4430-abd7-0e45b4150b34)
Also here is a video for reference:-
https://www.loom.com/share/c24a51640cb84ef0bb980fb6023fd0ab?sid=12d3bab8-2069-4d30-9dbf-461777c55aa9

**Comment by fracek** [comment]
Sorry for the late reply, I thought I did already. Yes I noticed the same bug so I'll see what can be done!

**Comment by fracek** [comment]
This should be fixed in v2. If not, feel free to reopen.
