### ISSUE TITLE
Usebalance of hook not showing balance

### ISSUE THREAD

**Issue by Sahitya777** [apibara/starknet-react#306]
![image](https://github.com/apibara/starknet-react/assets/77379621/225eb926-7d49-40d0-bb03-63e3daa0f2ab)
As you can see sometimes the useBalance of hook sometimes dosent show the balance and gives this error also whenever this error comes up this also shows up
![image](https://github.com/apibara/starknet-react/assets/77379621/8cfb1b44-6c87-4df8-8fa3-bf47d1d6a79b)

**Comment by fracek** [comment]
That errors is because the feeder gateway CORS headers are messed up. You should try the [next release of starknet-react](https://starknet-react.com/docs/getting-started) which uses JSON-RPC.
