### ISSUE TITLE
@starknet-react/core does not contain many packages

### ISSUE THREAD

**Issue by yj18523574287** [apibara/starknet-react#324]
![14951699100742_ pic](https://github.com/apibara/starknet-react/assets/29517645/838c3264-be32-4605-8197-58565dd63861)
![WeChat4390a23b9c533e71bfa65ffb9480ee66](https://github.com/apibara/starknet-react/assets/29517645/282aa5f5-e344-41d2-8384-30e58ed56ba4)
According to your tutorial, these packages cannot be imported correctly. I can't seem to find them without looking at the source code. Do you need to update your demo?

**Comment by IvanLudvig** [comment]
are you using the latest version of starknet-react?

**Comment by yj18523574287** [comment]
yes sir
________________________________
发件人: Ivan Ludvig ***@***.***>
发送时间: 2023年11月6日 14:09
收件人: apibara/starknet-react ***@***.***>
抄送: yu jiang ***@***.***>; Author ***@***.***>
主题: Re: [apibara/starknet-react] @starknet-react/core does not contain many packages (Issue #324)


are you using the latest version of starknet-react?

―

**Comment by fracek** [comment]
What's your project setup? Do you use next.js? Vite? Is the repo open source?

**Comment by okhaimie-dev** [comment]
I an facing the same issue, and I used NextJS / the recommended `create starknet` command

**Comment by fracek** [comment]
If I open your project, code completion in vs code work fine for me. I finished updating your project (i opened a pr in your repo) and after than `npm build` works fine without any error.

**Comment by fracek** [comment]
This one is fixed in v2
