### ISSUE TITLE
auto connect when page releod

### ISSUE THREAD

**Issue by ahmetoznar** [apibara/starknet-react#330]
![2023-11-08 23 00 47](https://github.com/apibara/starknet-react/assets/45452358/19c50f0a-e3a7-4ec3-8b38-00e0eb517ea8)
![2023-11-08 23 00 41](https://github.com/apibara/starknet-react/assets/45452358/f4ed55f7-e045-4049-b619-1c4c45ab9168)

I am facing with above error when i want to auto connect  to my wallet when my page reload. There might be an boolean like "shouldAutoConnect"

**Comment by fracek** [comment]
You can use the `autoConnect` option in `StarknetConfig` to enable this behaviour.
