### ISSUE TITLE
Return connector's chainId in `useAccount`

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#344]
At the moment, it's hard to tell if the currently selected network in the wallet matches one of the networks supported by the dapp. The hook `useNetwork` only returns the chain used by the dapp.

We should add a new return value `chainId: bigint | undefined` to the `useAccount` hook that returns the current connector's chainId (available through the `chainId` async call). Notice that in this case it only returns the chainId and not the chain since the selected chain may be a custom chain.

**Comment by edisontim** [comment]
Hey! Can I take this?
