### ISSUE TITLE
Create companion app to deploy arcade accounts

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#348]
Related to #347 

## Goal

Create a new Next.js 14 application that's used to deploy the arcade account for mobile apps. The app will be a simple Starknet React app that uses Tailwind + Shadcn for styling.

## Routes

 - `/setup`: this page is linked from the mobile app and is used to fund, deploy, and initialize arcade accounts. It receives all parameters through query parameters.
 - `/setup/completed`: at the end of the setup flow, redirect users to this page and tell them to go back to the mobile app.

## References

We can use the [burner account demo](https://starknet-react.com/demos/accounts) as a starting point for this application.

**Comment by josephchimebuka** [comment]
Is this issue still open I could handle it ASAP @fracek  I could create the next js app for deploying the project to the mobile app
