### ISSUE TITLE
Add manage account page to companion app

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#352]
Related to #347 Requires #348 

## Goal

Add a new `/manage` route to manage a specific arcade account. It should show permissions granted and a button to withdraw all funds from the arcade account and back to the main wallet.

**Comment by samueloh99** [comment]
Hi ! Can I take this issue ?

**Comment by fracek** [comment]
Hey @samueloh99 the work on this example is stalled for now. I need to review the related PRs before you can work on this.

**Comment by samueloh99** [comment]
@fracek ok !!

**Comment by martinvibes** [comment]
can i have this
