### ISSUE TITLE
Add `Explorer` interface and `useExplorer` hook

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#357]
All dapps link to block explorers (such as Starkscan or Voyager) from their interface. I believe we should add an interface to generate block explorers links.

## The `Explorer` interface

This interface simply provides methods to generate the url to a specific page.

```ts
interface Explorer {
  // link to a block
  block({ hash: string } | { number: string | number }): string;
 // link to a transaction
  transaction({ hash: string }): string;
  // link to a contract/account
  contract({ address }): string;
  // link to class hash
  class({ hash: string }): string;
}
```

## Configuration

We extend `StarknetConfig` to accept an _optional_ parameter `explorer` that takes as input an _explorer factory_. An explorer factory is a function with type:

```ts
export type ExplorerFactory<
  T extends Explorer = Explorer,
> = (chain: Chain) => T | null;
```

To keep the implementation simple, we store the factory (if any) in [`StarknetState`](https://github.com/apibara/starknet-react/blob/main/packages/core/src/context/starknet.tsx#L25) and instantiate the explorer in the `useExplorer` hook.

Users configure the explorer when they use `StarknetConfig`:

```tsx
import { StarknetConfig, voyager } from "@starknet-react/core";

function App() {
  return (
    <StarknetConfig provider={...} chains={...} explorer={voyager}>
     <Routes />
   </StarknetConfig>
  );
}
```

## Explorer implementations

We should put all explorer-related functions in `src/explorers` in the  `@starknet-react/core` package.

I propose the following layout:

 - `src/explorers/explorer.ts`: define `ExplorerFactory` and `Explorer`
 - `src/explorers/<impl>ts`: defines a specific explorer. For example, `src/explorers/voyager.ts` defines `VoyagerExplorer extends Explorer`  (the implementation) and `const voyager = (chain: Chain) => Explorer` (the factory).
 - `src/explorers/index.ts`: re exporters everything from the other files.

## Update `@starknet-react/chains`

We add the following property to `Chain`:

```ts
export type Chain = {
  // existing fields
  explorers: {
    [key: string]: string[];
  }
}
```

and then add them to `mainnet` and `goerli`:

```ts
export const goerli = {
  explorers: {
    starkscan: ['https://starkscan.co/'],
    voyager: ['https://voyager.online/'],
   // and so on
  }
}
```

## The `useExplorer` hook

This hook simply returns an object that implements the `Explorer` interface for the current network. If the  provider's `explorer`  is not configured or if for any other reason it's not possible to instantiate the explorer, the hook should throw an error since it's a bug that the developer must fix.

```ts
// definition
function useExplorer(): Explorer;

// usage
const explorer = useExplorer();
explorer.block({ hash: '0x123...' })
```

## Starknet block explorers

We should include at least the following explorers:

 - [Viewblock](https://viewblock.io/starknet)
 - [Stark Compass](https://www.starkcompass.com/)
 - [Starkscan](https://starkscan.co/)
 - [Voyager](https://voyager.online/)

**Comment by mgavillo** [comment]
Would be happy to take this

**Comment by fracek** [comment]
This is now released!
