### ISSUE TITLE
Using RPC Provider, but 'account' Object Still References 'feederGateway' which is deprecated

### ISSUE THREAD

**Issue by web3xDev** [apibara/starknet-react#358]
Currently, I am utilizing the RPC provider for my operations. However, I have noticed that the 'account' object still makes references to the deprecated 'feederGateway.' This inconsistency is a concern, as it may lead to compatibility issues and disrupt the functionality of the codebase.

Deprecation announcement: https://community.starknet.io/t/feeder-gateway-deprecation/100233

<img width="545" alt="provider" src="https://github.com/apibara/starknet-react/assets/121871183/3ef91aa8-c85b-4cb1-8341-31808b9241f1">

**Comment by fracek** [comment]
No worries!
