### ISSUE TITLE
Icon error when wallet is not installed

### ISSUE THREAD

**Issue by thannvn** [apibara/starknet-react#370]
Use `connectors` to render wallet list, icon of wallet will be error when wallet not installed

![image](https://github.com/apibara/starknet-react/assets/55594667/f421decb-bfe8-4288-8b0c-22e844078b01)

**Comment by mgavillo** [comment]
Yes saw it too, can do it quickly!

**Comment by thannvn** [comment]
@mgavillo @fracek Thank you

**Comment by fracek** [comment]
Argent and braavos now have the icon included even if they're notinstalled.
