### ISSUE TITLE
Support for sepolia network on rpc provider from starknet react core

### ISSUE THREAD

**Issue by Sahitya777** [apibara/starknet-react#382]
![image](https://github.com/apibara/starknet-react/assets/77379621/5fb20e13-f283-458f-a4c2-6dea70d44d35)
So i use infuraProvider from starknet react core i have configured sepolia network from chains but the rpc shows this error when i try to open the application. Code for the following :-
![image](https://github.com/apibara/starknet-react/assets/77379621/22d224f9-342e-4561-93b1-4bc6e36cabac)

**Comment by fracek** [comment]
I pushed a version of `@starknet-react/chains` that includes RPCs (public only atm) for Sepolia. Will close the issue once all RPC providers have been updated.
