### ISSUE TITLE
How to identify dapp on connect?

### ISSUE THREAD

**Issue by rsodre** [apibara/starknet-react#424]
Hello,

I can't find anywhere on the docs and examples...
How can we give a name and icon to our dapp before `connect()`?
It always uses the current url, even on the Demo, the dapp name is `starknet-react.com`.

On connect, my dapp name and icon should be here:

<img width="352" alt="Screenshot 2024-04-03 at 13 22 18" src="https://github.com/apibara/starknet-react/assets/229161/fdf40504-8bbd-4da3-9d36-11e66ccda789">

And after connection...

<img width="360" alt="Screenshot 2024-04-03 at 13 11 44" src="https://github.com/apibara/starknet-react/assets/229161/a2e2c8d3-23c2-472a-9a39-4f6534d331e1">

**Comment by fracek** [comment]
Good question, let me ask to the wallet providers because AFAIK there is no API for it.

**Comment by rsodre** [comment]
I think [StarknetKit](https://www.starknetkit.com/docs/getting-started#connection-parameters) can do it

**Comment by fracek** [comment]
I checked with argent and the icons/name come from their own database of dapps. The frontend has no control over it.

Going to close the issue since there's nothing we can do for it.
