### ISSUE TITLE
Contract deploy does not works with braavos injected wallet.

### ISSUE THREAD

**Issue by prix0007** [apibara/starknet-react#440]
Steps to Reproduce:
- Create a scaffold create react app
  - npx create-starknet-app@latest app_name debugger
- Connect Braavos with running sacffold application
- Navigate to scaffold deployer page: http://localhost:3000/scaffold-deployer
- Try deploying contract with Already declared class hash (i.e on sepolia:`0x045b176b50d6430f58655c25020d2012ce9d198f972f7e0e0e5296c8d7b3151a`)

Expected:
Wallet pop up for deploying contract on braavos

Result:
No action happens, keeping clicking deploy doesn't do anything.

Notes:
Works fine with ArgentX Injected wallet connect.

**Comment by prix0007** [comment]
Attaching SS from dependencies in scaffold at the time of creating issue
<img width="421" alt="Screenshot 2024-05-10 at 10 47 48 PM" src="https://github.com/apibara/starknet-react/assets/30095502/14d4a14e-dacd-4d30-8181-6e7300702f4c">

**Comment by Iwueseiter** [comment]
@prix0007 Please can I work on this?

**Comment by prix0007** [comment]
Please do that @Iwueseiter . Looking forward to your solution.

**Comment by Iwueseiter** [comment]
Alright

**Comment by prix0007** [comment]
Nope no error on logs, just the function call get's stuck. Works fine with argent wallet.

**Comment by prix0007** [comment]
Update:
There was an issue with Braavos Wallet and they have fixed it into prod. 
Maybe we can have a timeout in lib itself, else we can close the issue.

cc. @fracek

**Comment by avimak** [comment]
Greetings from Braavos team 👋 
Please try with Braavos v3.50.0 (and above) 🙏

**Comment by fracek** [comment]
Will close the issue for now! Thank you for reporting.
