### ISSUE TITLE
Release V3 alpha/beta

### ISSUE THREAD

**Issue by rsodre** [apibara/starknet-react#451]
I'm at a point where I can't stay on `starknet` v5 anymore, I have to upgrade to v6.
But `starknet-react` is stuck on v5, hooks do not work if my project resolves `starknet` v6.

**Please** publish the `@starknet-react/core` **next-v3 branch** as alpha or beta!

**Comment by fracek** [comment]
Hello, yes we finished migrating all (most) hooks to the new version and are going to release the next one. Curious to hear why you cannot use starknet v5 anymore? AFAIK it should not break until all the ecosystem migrated to starknet v6.

**Comment by rsodre** [comment]
I'm working with Dojo, and [dojo.js](https://github.com/dojoengine/dojo.js) already migrated to v6, preparing to add Paymaster support on execute calls.
With v5, I start getting errors, because they already use some new types.
With v6, some of your core hooks stop working.

I'm stuck, about to recreate some of your hooks just so I can continue working.
That's why I'm asking to release an alpha.

**Comment by fracek** [comment]
Do you need to support wallets like braavos and argent or you have a smart wallet? I'm happy to push a pre-release this week but in that case you'll need to implent your own connector to work with browser wallets (looks like braavos already works with v6 tho).

**Comment by fracek** [comment]
That sounds good. I'll start making pre-releases of v3 but wallet support is still not 100% complete. Worst case someone will have to implement an adapter for the v6 to v5 wallet api.

**Comment by jrcarlos2000** [comment]
jumping into this discussion, i have also faced issues with Argent when upgrading v5 -> v6. So far braavos is working well.

**Comment by rsodre** [comment]
I started testing wallets this week, useBlockNumber()` also has some issues, and I get all sort of weird errors.

A pre-release would be good!

**Comment by fracek** [comment]
Hello, I started publishing pre-releases (`3.0.0-beta.0` is the current one). I'm testing it with the most recent versions of braavos and argent.

**Comment by edulanasca** [comment]
Hi @fracek is there any docs we can start looking?

**Comment by fracek** [comment]
The preview is [available here](https://starknet-react-website.vercel.app/). Will add instructions on how to update shortly.

**Comment by gianalarcon** [comment]
Hi Team, any ETA of the stable version? Starknet-react is the core of our project. 
You are an amazing team, thank you so much for all your effort!

**Comment by fracek** [comment]
@gianalarcon  Sorry for the late reply, I missed this comment! You can already upgrade by switching to the `@next` tag. Everything is implemented and only small bugs need to be ironed out. Waiting for the full ecosystem to update before making a final release.

**Comment by jrcarlos2000** [comment]
gm Team, wondering when will the @next version have a stable released  ? @fracek 👀

**Comment by fracek** [comment]
There's still a couple of small items related to in-app wallets before we tag the release as latest. Want to avoid breaking changes after it's an official release.

**Comment by metalboyrick** [comment]
Hi @fracek , I was wondering whether the version on the main branch is the intended stable version? if not do you have an estimate time of the release? I've noticed significant performance drops on the v3 account connections compared to its predecessors.

**Comment by metalboyrick** [comment]
@fracek thanks for the demo! very helpful!

As for how i concluded the perf issue, I noticed that when trying to connect, it takes a while for update the connected state of the wallet (from `useAccount`, `disconnected` to `connected`). I've also noticed that argentX is worse in the duration of connection. This did not happen in the previous version. Do you have any indication of potential issues and how to fix?

Slow argentX: 
<img width="874" alt="image" src="https://github.com/user-attachments/assets/35c9c9c1-b770-49e6-9c23-8c1da8f8944b">

**Comment by fracek** [comment]
The issue seems to be related to the new `wallet.request` API. I will double check if there's also any issue on our side, but if the issue is slow response from wallets there's not much we can do.

**Comment by metalboyrick** [comment]
@fracek Thanks for the hard work!
