### ISSUE TITLE
[Type] useAccount.address should return an Address type

### ISSUE THREAD

**Issue by FabienCoutant** [apibara/starknet-react#452]
`useAccount()` hook return the following type: 

```
/** Value returned from `useAccount`. */
export type UseAccountResult = {
  /** The connected account object. */
  account?: AccountInterface;
  /** The address of the connected account. */
  address?: string;
  /** The connected connector. */
  connector?: Connector;
  /** Connector's chain id */
  chainId?: bigint;
  /** True if connecting. */
  isConnecting?: boolean;
  /** True if reconnecting. */
  isReconnecting?: boolean;
  /** True if connected. */
  isConnected?: boolean;
  /** True if disconnected. */
  isDisconnected?: boolean;
  /** The connection status. */
  status: AccountStatus;
};
```

The `address` should be typed as `Address` instead of `string`

**Comment by MariangelaNM** [comment]
Hello,

I have extensive experience working with React and I can work on this issue. The solution involves adjusting the address property in UseAccountResult to use the Address type.

**Comment by Benjtalkshow** [comment]
@FabienCoutant 

I want to help fix the issue where useAccount.address should return an Address type. I am good with React and TypeScript. I can make this change quickly and correctly. 

Please assign this issue to me.
Thanks,

**Comment by fracek** [comment]
Good suggestion. Will be in v3.

**Comment by fracek** [comment]
The goal is to have a `getAddress` function that validates the address and returns `0x${string}`. That way it catches bugs related to passing things that are not addresses so functions that expect addresses.

**Comment by Benjtalkshow** [comment]
@fracek ,
 I'd love to take on this task. This is my second comment on this issue. I have extensive knowledge of React and TypeScript types, and I'll deliver a solution to this issue within a short period of time.

**Comment by fracek** [comment]
@Benjtalkshow that sounds good. Can you open a PR against the `develop` branch where you add the `getAddress` helper (in an `utils.ts` file for example) that simply invokes `validateAndParseAddress` from starknet.js and casts the result as `0x${string}`?

**Comment by PedroCo3lho** [comment]
Hello @fracek isn't this issue already fixed here: 

https://github.com/apibara/starknet-react/blob/2b08aa3f8e9b8140b19d5989ca72cef62a531200/packages/core/src/hooks/use-account.ts#L19-L37

**Comment by Benjtalkshow** [comment]
> @Benjtalkshow that sounds good. Can you open a PR against the `develop` branch where you add the `getAddress` helper (in an `utils.ts` file for example) that simply invokes `validateAndParseAddress` from starknet.js and casts the result as `0x${string}`?

@fracek ,
I am just seeing that you mentioned me. Am I still eligible to open a PR? I am available and ready to hop on the issue as soon as possible.

**Comment by fracek** [comment]
Yes of course! Since I commented I made some changes so now you should make a PR against the `main` branch. BTW if you wait ~10 days or so you can do this work as part of the next OD Hack

**Comment by Benjtalkshow** [comment]
> Yes of course! Since I commented I made some changes so now you should make a PR against the `main` branch. BTW if you wait ~10 days or so you can do this work as part of the next OD Hack

Ok. I will wait then. Thanks a lot. Can I get the telegram group link?

**Comment by fracek** [comment]
We will release the telegram group once OD Hack starts!

**Comment by salvadormartin3z** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Im interesting into manage states of React; so i could be solve this problem with good actitude

### How I plan on tackling this issue
I would firts understand the structure of the useAccount Hook to then see change the Address

**Comment by martinvibes** [comment]
can I work on this issue @FabienCoutant

**Comment by od-hunter** [comment]
Hi @fracek & @FabienCoutant , please can I be assigned this issue? This would be my first time contributing to this ecosystem.

**Comment by GoSTEAN** [comment]
@FabienCoutant Can I work on this issue?

**Comment by ShantelPeters** [comment]
Can i please be assigned to this issue @fracek

**Comment by jaipaljadeja** [comment]
> Can i please be assigned to this issue @fracek

@ShantelPeters please apply via OnlyDust : )

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I'm a frontend developer, my first time contributing to this repo it would take me a maximum of 4 working day to complete this issue and I have over 30 + contributions

### How I plan on tackling this issue
in intend to solve this issue in following this step: 
1. Update the Type Definition:
I would modify the UseAccountResult type definition to replace the string type for the address field with the Address type.

2. Ensure Address Type is Correctly Defined:
I will make sure that the Address type is correctly defined in your project. This type should be a stricter type definition that represents a valid blockchain address.

3. Update Usage Across the Codebase:
After updating the type definition, i will ensure that all places in the codebase where useAccount() is used or where the address field is accessed are updated to reflect this new type definition. This might include updating function parameters, state variables, or any other structures that expect an Address type.

4. Testing:
After making these changes, i will test the application to ensure that the new type definition does not introduce any issues. I will ensure that the address is being handled correctly and that type-checking passes without errors.

**Comment by sanieni6** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I am Luis Sanchez, a React developer with extensive experience in both React and TypeScript. My expertise includes developing scalable and maintainable front-end architectures using modern React practices, TypeScript for robust typing, and a strong focus on UI. I am also a proud member of Dojo Coding where I've been learning about web3 (starknet + cairo). My familiarity with TypeScript will be particularly beneficial in ensuring that the useAccount hook accurately uses the Address type, enhancing type safety and code reliability within the project.

### How I plan on tackling this issue
To solve the issue with the useAccount hook in starknet-react, I would take the following steps:

1. Review Existing Code: Begin by reviewing the current implementation of the useAccount hook to understand how the address is being handled and integrated across the application.

2. Define the Address Type: Define the Address type in TypeScript, ensuring it aligns with the requirements of StarkNet and provides the necessary validations or utilities that are more specific than a general string type.

3. Refactor the Hook: Update the useAccount hook to replace the address type from string to the newly defined Address type. This involves not only changing the type but also ensuring that any transformations or uses of the address data throughout the application are compatible with the new type definition.

4. Testing: Rigorously test the updated hook in various scenarios to ensure that it behaves as expected without any side effects. This includes testing the interaction with the StarkNet blockchain and any front-end components that utilize this hook.

**Comment by Benjtalkshow** [comment]
@fracek ,
You said I should work on this issue during this ODHack. Can you assign the issue to me now? I already applied through onlydust.

**Comment by Jemiiah** [comment]
@fracek i drop the issue on telegram implying I would do the work

**Comment by fracek** [comment]
> Hello @fracek isn't this issue already fixed here: 
> 
> https://github.com/apibara/starknet-react/blob/2b08aa3f8e9b8140b19d5989ca72cef62a531200/packages/core/src/hooks/use-account.ts#L19-L37

Hey, yes that specific issue is solved but we need the `getAddress` helper still.

**Comment by fracek** [comment]
Hey @Benjtalkshow you need to add the getAddress helper I described above.

**Comment by Benjtalkshow** [comment]
> Hey @Benjtalkshow you need to add the getAddress helper I described above.

Alright. Thanks for giving me the oppurtunity
