### ISSUE TITLE
useEstimateFees returns "Invalid Params, missing non-optional param: simulation_flags" 

### ISSUE THREAD

**Issue by TudorEsan** [apibara/starknet-react#455]
If I try to get the estimated fee I get this rpc error. Additionaly the useEstimateFees hook does not give a ts error that I need to fill other required parameters

rpc error:
```
{
    "jsonrpc": "2.0",
    "id": 0,
    "error": {
        "code": -32602,
        "message": "Invalid Params",
        "data": "missing non-optional param: simulation_flags"
    }
}
```

```ts
  const calls = useMemo(() => {
    if (!address || !contract) return [];
    const nominatedAmount = nominateNumber(
      formValues.amount,
      formValues.token.decimals
    );

    return contract.populateTransaction.transfer(
      formValues.toAddress,
      cairo.uint256(nominatedAmount)
    );
  }, [contract, address]);

  const { data: fee, isLoading: isFeeLoading } = useEstimateFees({
    calls,
    watch: true,
  });
```

**Comment by WhizIkem** [comment]
Hi there,

I've done some research on the useEstimateFees hook and encountered information regarding missing parameters, specifically simulation_flags. It seems this might be causing the issue. I'm interested in contributing to resolving this problem. Could you provide more details or confirm if this parameter needs to be included?

Looking forward to collaborating on this!

Best,
WhiZ

**Comment by Benjtalkshow** [comment]
Hello @TudorEsan,

I am an experienced JavaScript developer, and after my research on this issue, I can assure you that I can take it:

## My Analysis
The error message suggests that the `simulation_flags` parameter, which is non-optional, is missing from the request. This parameter is likely required by the RPC endpoint but is not being included in the `useEstimateFees` call.

## My Proposed Solution
- Include the Missing Parameter:
Ensure that the `simulation_flags` parameter is included in the `useEstimateFees` hook call. This might involve modifying the hook to accept this parameter and pass it along with the request.

- Update the Hook Usage:
Update the component where `useEstimateFees` is used to provide the necessary `simulation_flags`.

- TypeScript Enhancements:
Enhance the TypeScript definitions to ensure that missing required parameters, like `simulation_flags`, are flagged by TypeScript. This will help prevent similar issues in the future.

Thank you, and I am looking forward to getting assigned to this task.

**Comment by fracek** [comment]
What RPC version are you using? It could be you're using an RPC version (0.7) that's newer than what's supported by starknet react  v2 (RPC 0.6).

**Comment by TudorEsan** [comment]
yes im using the latest blast version prob its 0.7. thanks for answering i ll mark it as closed!
