### ISSUE TITLE
useAccount with onConnect callback functions causes maximum update depth exceeded

### ISSUE THREAD

**Issue by TudorEsan** [apibara/starknet-react#458]
when passing a callback function to the useAccount hook the app will continuously rerender.  

this is the code that causes the bug:
```ts
export const DAppProvider = () => {
  useAccount({
    onConnect: () => {
       console.log('Connected to StarkNet');
     },
    // onDisconnect: () => {
    //   console.log('Disconnected from StarkNet');
    // },
  });

  return null;
};
```
I'm using   "@starknet-react/core": "^2.8.3" and nextjs v14.1

the error i get:
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```
<img width="537" alt="Screenshot 2024-07-02 at 11 18 22" src="https://github.com/apibara/starknet-react/assets/55596191/e98ba512-ac67-4b63-b2e6-e8b1bec35de1">

**Comment by od-hunter** [comment]
Can I be assigned this? I’m ready to work

**Comment by fracek** [comment]
I removed the callbacks in v3 because they were causing too many issue. You should use `useEffect` with the address/account in the dependency list to invoke a function when the value changes.

**Comment by fracek** [comment]
Closing because there is no way to fix it and in v3 won't be an issue.
