### ISSUE TITLE
Web GUI 

### ISSUE THREAD

**Issue by domanost** [apibara/starknet-react#461]
After install

Frontend states : "Get started by editing pages/index.tsx"  When it is named and located at : "app/pages.tsx" 

Hyperlinks not noticeable  same color and background. (suggest text to white for contrast) 

![starkreact](https://github.com/apibara/starknet-react/assets/1761621/2273dc27-6de2-4985-a471-8239768b8dc2)

I don't the see companion-app in the Dev branch.  Sorry new but learning.

**Comment by fracek** [comment]
We're reorganizing things for v3, so I will close this issue.

**Comment by domanost** [comment]
I see now, I was able to spin up V3.
