### ISSUE TITLE
Handle Absent Injected Wallet

### ISSUE THREAD

**Issue by Realkayzee** [apibara/starknet-react#463]
**Handle Absent Injected Wallet**

In a situation where users don't have any injected wallet installed, developers are meant to receive a response, so as to handle what to display to users. Doing this will help increase user experience

**Comment by Benjtalkshow** [comment]
@Realkayzee ,

I would love to work on this issue. I have extensive knowledge of React and TypeScript and expertise in building React hooks. Here is my proposed solution:

- I will focus on modifying `packages/core/src/connectors/injected.ts` to handle absent wallets.
- Update the `InjectedConnector` class to detect the absence of injected wallets and throw a `ConnectorNotFoundError` if no wallet is found.
- I will ensure wallet detection is performed using the `getInstalledWallets()` function, which checks the window object for injected wallets.
- Modify the `connect()` method to provide feedback when no wallet is detected.
- In the React component, i will handle the `ConnectorNotFoundError` to display a user-friendly message or modal, guiding users to install a wallet if none is found.

**Comment by fracek** [comment]
This is already possible by getting the `connectors` list (from the `useConnect` hook, docs is currently wrong) and checking they're `available`.
