### ISSUE TITLE
useStarkProfile - in Lastest Version 2.0.0 -next.7

### ISSUE THREAD

**Issue by karasbuilder** [apibara/starknet-react#467]
I view document of home page : starknet-react. com
Have a hook is useStarkProfile 
but I can not import that hook in latest version , is it deprecated . Can you give me information about this?
<img width="1322" alt="Screenshot 2024-07-18 at 18 31 33" src="https://github.com/user-attachments/assets/68633e0f-ac06-40c7-ab7f-3a34ca42c76b">

**Comment by fracek** [comment]
Which version are you using? What error message do you get?
