### ISSUE TITLE
Add getNonceForAddress hook

### ISSUE THREAD

**Issue by NGUYENDANGVU-coder** [apibara/starknet-react#470]
I want get Nonce For Address

**Comment by ShantelPeters** [comment]
@NGUYENDANGVU-coder can I be assigned to this ?

**Comment by fracek** [comment]
Yes I'm open to adding this hook.

**Comment by ShantelPeters** [comment]
@fracek can I work on this ?

**Comment by fracek** [comment]
Hey @ShantelPeters we already have someone working on this sorry.

**Comment by fracek** [comment]
This will be in the next release dropping soon.
