### ISSUE TITLE
Add contributing.md file for new contributors.

### ISSUE THREAD

**Issue by deeseeker** [apibara/starknet-react#485]
TL;DR
Hello @fracek,

I've been working on an issue and encountered some challenges related to setup and dependencies. I checked for any existing guides but couldn't find one.

If we don't have such documentation yet, creating a comprehensive guide or a CONTRIBUTING.md file outlining the setup process, common issues, and best practices would be very valuable. It would help new contributors get up to speed more quickly and avoid common pitfalls.

Thanks for considering this!

**Comment by ooochoche** [comment]
@deeseeker I can handle this

**Comment by martinvibes** [comment]
hello @deeseeker i would love to work on this if i'm giving the opportunity :)

**Comment by jaipaljadeja** [comment]
Hey @deeseeker, Just added a [CONTRIBUTION.md](https://github.com/apibara/starknet-react/blob/main/CONTRIBUTING.md), i hope it will clear your doubts.
