### ISSUE TITLE
Add source code snippet to demo pages

### ISSUE THREAD

**Issue by rsodre** [apibara/starknet-react#518]
Each [demo page](https://www.starknet-react.com/demo) should have the source code available in a tab or something.
At least a link to the demo page in the repository, so we can see how that feature works.

**Comment by ooochoche** [comment]
@rsodre please is this an open issue

**Comment by fracek** [comment]
Agree with this. We should have a link to GitHub (so that it's always up-to-date) + a description of what the demo is showing.

**Comment by fracek** [comment]
Hey @ooochoche, yes you can work on it.

Follow the following format please:

```
<Brief description of the demo>

[Link to GitHub](https://github.com/apibara/starknet-react/blob/main/docs/components/demo/<demo-name>.tsx)
```

For example:

```
This demo shows how to access the currently connected account and its address.

[Link to GitHub](https://github.com/apibara/starknet-react/blob/main/docs/components/demo/account.tsx)
```

**Comment by ooochoche** [comment]
@fracek Thank you. I will get on it.

**Comment by fracek** [comment]
You can open a PR and I will review it. No need to have the issue assigned.
