### ISSUE TITLE
Transaction status changed notification

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#52]
Some apps show notifications when the transaction status changes. The library should provide a mechanism for developers to register a callback invoked every time a transaction status changes.

**Comment by fracek** [comment]
The idea is to add a set of `onAccepted`, `onAcceptedOnL1` etc arguments to the hook. Every time the tx status changes, the user-provided callback is called.

**Comment by J4ckyLIM** [comment]
Hi can I take this contribution ?

**Comment by fracek** [comment]
That sounds good! It looks like it can be done together with #174.

**Comment by fracek** [comment]
Fixed in #174
