### ISSUE TITLE
bug: disconnecting from the wallet UI doesn't trigger anything

### ISSUE THREAD

**Issue by enitrat** [apibara/starknet-react#520]
repro:

Go to any starknet dapp (like Ekubo), disconnect from your Argent / Braavos wallet: nothing changes in the Ekubo UI, the wallet stays connected but attempting to click swap will just do nothing.

**Comment by od-hunter** [comment]
Hi @enitrat , please is this open for contribution? If yes, I’d love to be assigned this.

**Comment by enitrat** [comment]
@od-hunter this is a bug report

**Comment by od-hunter** [comment]
> @od-hunter this is a bug report

Ok ser

**Comment by fracek** [comment]
Thanks. Will look into it.
