### ISSUE TITLE
Kakarot's `wallet_addInvokeTransaction` doesn't return the same data format as Starknet wallets

### ISSUE THREAD

**Issue by enitrat** [apibara/starknet-react#530]
Starknet connectors return an `InvokeFunctionResponse`, which is an object like:
```
type Result = {
  transaction_hash: string,
  ...
}
```

while Kakarot connectors returns the transaction hash directly.

```
type Result = string
```

Also, I believe it would be interesting to return the starknet transaction hash, if possible.
Most apps today are waiting for the transaction status to be accepted on L2 to send a confirmation to the user.
If we return the _evm_ tx hash on kakarot, this never ends.

cc @eikix

**Comment by ooochoche** [comment]
@enitrat Can I jump on this?
