### ISSUE TITLE
Use multicall in `useStarkNetCall`

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#6]
The hook should batch together all registered calls and send only one multicall request, then deduplex the output back to the original caller.

**Comment by TotalPizza** [comment]
@fracek
Hey, I might be interested in implementing this.
Is this being worked on atm?

**Comment by fracek** [comment]
We have a contributor that started looking into this! Let me get back to you soon with more information.

**Comment by TotalPizza** [comment]
All good :)
It's probably better if I don't do it :D

**Comment by fracek** [comment]
Duplicate of #291
