### ISSUE TITLE
Add invoke method to transaction manager

### ISSUE THREAD

**Issue by starwalker00** [apibara/starknet-react#70]
Hello,

It would be useful to be able to get the method involved in the transaction ( and maybe more? ) when using ```useStarknetTransactionManager```.

TCALSS :

**From this:**
https://github.com/auclantis/starknet-react/blob/a09a87b87e1afddb23a766a5990903c599b5e603/packages/core/src/hooks/invoke.ts#L95

**To this:**
```addTransaction({ status: response.code, transactionHash: response.transaction_hash, method:method }) ```

Thank you.

**Comment by fracek** [comment]
I think we should call the extra field something like `description` or `summary`. We should update `invoke` to also accept a parameter to set this field on the transaction.

@dhruvkelawala also added something similar for Solve 2 Mint.
