### ISSUE TITLE
disconnect wallet

### ISSUE THREAD

**Issue by rootulp** [apibara/starknet-react#79]
It seems like starknet-react doesn't support disconnecting the connected wallet. Would maintainers consider supporting a `disconnect()`?

Ref:
https://github.com/apibara/starknet-react/blob/main/packages/core/src/connectors/base.ts#L20=

**Comment by tarrencev** [comment]
I think this would be a welcomed contribution!

**Comment by fracek** [comment]
Yep, I'm happy to review a PR for this.
