### ISSUE TITLE
Improve rendering amount using some hooks

### ISSUE THREAD

**Issue by ltoussaint** [apibara/starknet-react#83]
Hello there,

I have an issue regarding the number of renders for component using some hooks.

Some of them (like `useStarknetCall` or `useStarknetBlock`) automatically refresh their data when a new block occures.
The problem is that even when there are no new blocks, it causes a render of all components (and by extension children) using those hooks.

I created a [repository](https://github.com/ltoussaint/starknet-react-repro/tree/too-many-rerender) to reproduce the problem, you can find it on the branch ["too-many-rerender"](https://github.com/ltoussaint/starknet-react-repro/tree/too-many-rerender).
We will see the difference between the number of rendering and the number of real new blocks.

I know that with React, a lot of elements are memoized (callbacks, state, computed data, ...) but in some cases it can be a problem.
Especially when I used those hooks in a context/provider on top of the app, then it causes the try to rerender the whole tree.
And as you may guess, I don't want to explicitly memoize all my components.

I didn't investigate much, but maybe something could be improved with `useStarknetBlock` where it seems the `data` property change even if the block is not new.

**Comment by fracek** [comment]
Thank you for creating a repo to reproduce the issue. I will look into it.

**Comment by fracek** [comment]
Fix in #88. Now the block number updates much less often.

**Comment by ltoussaint** [comment]
Thanks a lot
