### ISSUE TITLE
nit: useStarknet documentation is missing connectors variable

### ISSUE THREAD

**Issue by Pet3ris** [apibara/starknet-react#92]
https://apibara.github.io/starknet-react/hooks/starknet

The connectors variable here: https://github.com/apibara/starknet-react/blob/51c0803eb7294552c4913c9592b0a69913a16ef1/packages/core/src/providers/starknet/model.ts#L8 is missing from the above documentation.

**Comment by fracek** [comment]
Will update the docs, thank you for this.
