### ISSUE TITLE
Possible violation of types when using `useStarknet`

### ISSUE THREAD

**Issue by Pet3ris** [apibara/starknet-react#93]
I'm observing the following object when connecting via `useStarknet`:

![image](https://user-images.githubusercontent.com/224585/166420062-5108b5a8-16e4-4d32-847c-2da74453850c.png)

This seems to be in violation of the types seen here:

https://github.com/apibara/starknet-react/blob/51c0803eb7294552c4913c9592b0a69913a16ef1/packages/core/src/providers/starknet/model.ts#L4

```typescript
export interface StarknetState {
  account?: string
  connect: (connector: Connector) => void
  library: ProviderInterface
  connectors: Connector[]
  error?: Error
}
```

Should this mean that `connectors` etc. need to be marked as `?`?

**Comment by fracek** [comment]
This is now fixed.
