### ISSUE TITLE
What is the idiomatic way for checking if an account is connected?

### ISSUE THREAD

**Issue by Pet3ris** [apibara/starknet-react#94]
In wagmi, the idiomatic way to check if the wallet is connected seems to be to check `accountData` using `useAccount`.

Is it fair to say that the idiomatic way for `starknet-react` is to check the `account` variable returned from the `useStarknet` hook?
https://apibara.github.io/starknet-react/hooks/starknet

**Comment by fracek** [comment]
Correct, if the user is not connected account will be `undefined`.
