### ISSUE TITLE
Issue when both ArgentX and Braavos wallets enabled

### ISSUE THREAD

**Issue by Pet3ris** [apibara/starknet-react#97]
Running into this issue on Brave where if both ArgentX and Braavos wallets are enabled, I get the following error:

![Screen Shot 2022-05-03 at 3 12 24 PM](https://user-images.githubusercontent.com/224585/166470013-70a2b986-62f1-4e37-af35-a22f82b64889.png)

**Comment by fracek** [comment]
Related to #77. Need to fix this ASAP.

**Comment by avimak** [comment]
@fracek the root cause actually sits in argent's extension, see [here](https://github.com/argentlabs/argent-x/blob/develop/packages/extension/src/inpage/index.ts#L161)

**Comment by fracek** [comment]
Where should we track this issue? /cc @janek26

**Comment by Pet3ris** [comment]
This is a good tweet from Vitalik of the benefit of testing with multiple wallets: https://twitter.com/VitalikButerin/status/1531771109602799617.

**Comment by fracek** [comment]
#109 fixes this. Let's get it merged.

**Comment by fracek** [comment]
This is now fixed.
