### ISSUE TITLE
UseCallContract response type loses type information for result

### ISSUE THREAD

**Issue by Pet3ris** [apibara/starknet-react#98]
The call contract response from starknet.js returns an array of strings: https://github.com/0xs34n/starknet.js/blob/cd88fc8747897002b48c48da94c4da60ba739e87/src/types/api.ts#L145.

```typescript
export type CallContractResponse = {
  result: string[];
};
```

However, the corresponding type in `starknet-react` is an array of `any`. Could this be restricted to an array of strings?

https://github.com/apibara/starknet-react/blob/51c0803eb7294552c4913c9592b0a69913a16ef1/packages/core/src/hooks/call.ts#L60

**Comment by fracek** [comment]
The type definition in starknet.js is wrong. The return value is a weird array with keys(!), the objects are deserialized from a flat felt array to their type (so for example `balanceOf` has one element that is an `uint256` struct). I talked with @janek26 about this, and they're open to a PR that adds type safety around contract calls.

**Comment by fracek** [comment]
I will :)

**Comment by fracek** [comment]
This is still an issue in v2.

**Comment by HumbertoTM10** [comment]
Is this available to pick up?

**Comment by fracek** [comment]
This can be done as part of the work on v3. I will try to organize the effort so you can contribute to it.

**Comment by fracek** [comment]
Hey @HumbertoTM10 , you can work on this. Make sure to start your work from `next-v3` and make the PR against that branch. A good starting point is studying [abi wan](https://github.com/keep-starknet-strange/abi-wan-kanabi) and see how it works.

**Comment by HumbertoTM10** [comment]
Hey @fracek, got it! Assign it to me, will work on it!

**Comment by fracek** [comment]
Done. Make sure to [add tests to test types](https://vitest.dev/guide/testing-types) in your PR.

**Comment by Pet3ris** [comment]
Love it

**Comment by fracek** [comment]
Available in v3.
